// The BRXEL wordmark, kept for the hidden /brand pages. Paths generated by brand-logo/build_logo.py — rebuild there rather than editing by hand.
const WORD = "M0 0 L92 0 L110 18 L110 39.5 L118 47.5 L118 82 L100 100 L0 100 Z M23 21 L87 21 L87 39.5 L23 39.5 Z M23 60.5 L95 60.5 L95 79 L23 79 Z M127 0 L227 0 L245 18 L245 60.5 L205.5 60.5 L245 100 L212.47 100 L172.97 60.5 L150 60.5 L150 100 L127 100 Z M150 21 L222 21 L222 39.5 L150 39.5 Z M291.77 46.11 L253.08 0 L283.1 0 L306.78 28.22 Z M313.31 71.78 L328.32 53.89 L367.01 100 L336.99 100 Z M378.83 0 L468.83 0 L468.83 21 L383.83 21 L383.83 39.5 L456.83 39.5 L456.83 60.5 L383.83 60.5 L383.83 79 L468.83 79 L468.83 100 L378.83 100 L360.83 82 L360.83 18 Z M477.83 0 L500.83 0 L500.83 79 L577.83 79 L577.83 100 L495.83 100 L477.83 82 Z";
const STROKE = "M253.08 100 L336.99 0 L367.01 0 L283.1 100 Z";

/**
 * The BRXEL wordmark. Letters take the current text colour, so it flips with `.on-light`;
 * the rising stroke of the X stays Ember. `mono` draws that stroke in the text colour too
 * (for use on an Ember ground).
 */
export default function BrxelLogo({ className = "h-5 w-auto sm:h-6", mono = false, title = "BRXEL" }) {
  return (
    <svg
      viewBox="0 0 577.83 100"
      width={577.83}
      height={100}
      className={className}
      role="img"
      aria-label={title}
      focusable="false"
    >
      <path fill="currentColor" fillRule="evenodd" d={WORD} />
      <path fill={mono ? "currentColor" : "#E85A24"} d={STROKE} />
    </svg>
  );
}
